### ISSUE TITLE
Notify people the date is in dd/mm/yy format

### ISSUE THREAD

**Issue by SimpleBinary** [Dandigit/dandigit.com#2]
@Dandigit This is something you do not have to do, but I am going to say it anyway. 
![image](https://user-images.githubusercontent.com/40658215/50674735-a4c18300-1034-11e9-9ca9-e36dad31cff5.png)
You can see that in the picture there is the date, but some people would interpret that as 1/4/19.
I recommend you do this as to avoid confusion:
 
![image](https://user-images.githubusercontent.com/40658215/50674802-3d580300-1035-11e9-9184-cfd10c17821a.png)

Remember, this is just what _I_ think you should, so don't feel like you have to do this.
- SimpleBinary

**Comment by Dandigit** [comment]
@SimpleBinary If some American sees this and reads the date incorrectly, I don't care. Perhaps I'll just add an `alt` attribute for when people hover over. Probably not though. Why the US decided to stick with MM/DD/YY is beyond me.

**Comment by SimpleBinary** [comment]
@Dandigit Lovely new look for the New Year. It is really good. I've also decided to redesign my website. 👍
